kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-config
  namespace: ovn-kubernetes
data:
  k8s_apiserver: https://10.0.2.18:6443
  net_cidr:      10.244.0.0/16
  svc_cidr:      10.96.0.0/12
  OvnNorth:      tcp://10.0.2.18:6641
  OvnSouth:      tcp://10.0.2.18:6642
  sriov_pf:      ""
  encap_type:    ""

